brew 'ansible'
brew 'atool'
brew 'awscli'
brew 'bash'
brew 'chruby', args: ['HEAD']
brew 'coreutils'
brew 'ctags'
brew 'elinks'
brew 'elixir'
 brew 'emacs', args: ['HEAD', 'with-cocoa']
# brew 'emacs', args: ['with-cocoa']
brew 'exiftool'
brew 'figlet'
brew 'findutils'
brew 'fortune'
brew 'fzf', args: ['HEAD']
brew 'ghostscript'
brew 'git'
brew 'gnu-sed'
brew 'highlight'
brew 'imagemagick'
brew 'jmeter', args: ['with-plugins']
brew 'jq'
brew 'lame'
brew 'libcaca'
brew 'libxml2'
brew 'libxslt'
brew 'libyaml'
brew 'lynx'
brew 'maven'
brew 'mediainfo'
brew 'mongodb'
brew 'mysql'
brew 'ncdu'
brew 'openssl'
brew 'poppler'
brew 'postgresql'
#brew 'python3'
brew 'ranger'
brew 'reattach-to-user-namespace'
brew 'ruby-install'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'transmission'
brew 'unrar'
brew 'vim', args: ['with-override-system-vi']
brew 'watch'
brew 'w3m'
brew 'wget'
brew 'zsh'

# tap 'burntsushi/ripgrep'
# brew 'burntsushi/ripgrep/ripgrep-bin'
brew 'ripgrep'

# tap 'homebrew/dupes'
# brew 'gnugrep', args: ['with-default-names']

tap 'caskroom/cask'
cask 'appcleaner'
cask 'calibre'
cask 'chefdk'
cask 'docker'
#cask 'docker-toolbox'
cask 'iterm2-nightly'
cask 'java'
cask 'kindle'
cask 'macdown'
cask '1password'
cask 'sequel-pro'
cask 'slack'
cask 'steam'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'wkhtmltopdf'

brew 'mas'
mas 'Xee3', id: 639764244
mas 'iMovie', id: 408981434
mas 'Clear', id: 504544917
mas 'Xcode', id: 497799835
mas 'AffinityPhoto', id: 824183456
