# Homebrew Brewfile
# run with: brew bundle /path/to/Brewfile

# update Homebrew
update

# upgrade install formulae
upgrade

install openssl
install coreutils
install findutils
install bash
install libxml2
install libxslt
install libyaml
install mongodb
install tig
install reattach-to-user-namespace
install tmux
install the_silver_searcher
install sqlite
install awscli
install bash-completion
install ctags
install imagemagick
install maven
install watch
install zsh
install jq
install gnu-sed
install macvim --override-system-vim

# set up brew cask
tap phinze/homebrew-cask
install brew-cask
tap caskroom/versions

# casks
cask install bettertouchtool
cask install iterm2-nightly
cask install virtualbox
cask install vagrant
cask install alfred
cask alfred link
cask install dropbox
#cask install caffeine
cask install evernote
cask install steam
cask install mou
cask install adium
cask install firefox
cask install google-chrome
cask install sequel-pro
cask install spotify
cask install nvalt
cask install appcleaner
cask install fantastical
cask install bowtie
cask install vlc

# these are currently coming from the Mac App Store, not Cask
# xee
# kypass companion
# clear

# remove old cruft
cleanup

