#!/bin/bash
set -euo pipefail

#
# bootstrap init script
#
# Usage:
#   * For a brand new machine, clone the bootstrap repo and launch this script
#   * Any time the clone is updated, re-run this script
#
# If you'd like to symlink the dot files to a location other than $HOME,
# export the variable BOOTSTRAP_TARGET_DIR before calling this script.
#
# If you'd like to use a shell other than the /usr/local/bin/mksh,
# export the variable DESIRED_SHELL before calling this script.
#

bootstrap_dir=$(dirname "${BASH_SOURCE}")
cd $bootstrap_dir
bootstrap_dir=$(pwd)
target_dir=${BOOTSTRAP_TARGET_DIR:-$HOME}
DESIRED_SHELL=${DESIRED_SHELL:-}

# this shell will be added to /etc/shells if absent and set as the default
if [[ -z "$DESIRED_SHELL" ]]; then
  if [[ -e "/bin/mksh" ]]; then
    DESIRED_SHELL=/bin/mksh
  elif [[ -e "/usr/local/bin/mksh" ]]; then
    DESIRED_SHELL=/usr/local/bin/mksh
  else
    echo 'Cannot locate mksh and DESIRED_SHELL is not set!'
    exit -1
  fi
fi

function running_mac_os() {
  [[ "$OSTYPE" == "darwin"* ]] && return
  false
}

function running_debian() {
  (command -v apt-get >/dev/null) && return
  false
}


# --- --- --- --- --- --- ---
# create dot file symlinks
# --- --- --- --- --- --- ---

echo "Symlinking dot files..."
function process_dot_dir() {
  dir=$1
  shopt -s dotglob
  for f in "$dir"/*; do
    if [[ -d "$f" ]]; then
      process_dot_dir "$f"
      continue
    fi
    target="$target_dir/${f//$bootstrap_dir\/dots\//}"
    if [[ -e "$target" ]]; then
      echo "$target already exists - skipping"
      continue
    else
      if [[ "${target%/*}" != "$target_dir" ]]; then
        cmd="mkdir -p ${target%/*}"
        echo "$cmd"
        eval "$cmd"
      fi
      cmd="ln -s \"$f\" \"$target\""
      echo "$cmd"
      eval "$cmd"
    fi
  done
  shopt -u dotglob
}
process_dot_dir "$bootstrap_dir/dots"


# --- --- --- --- --- --- ---
# fonts
# --- --- --- --- --- --- ---

if running_mac_os; then
  echo "Installing fonts..."
  for f in "$bootstrap_dir/fonts"/*; do
    target="$target_dir/Library/Fonts/${f//$bootstrap_dir\/fonts\//}"
    if [[ -e "$target" ]]; then
      echo "$target already exists - skipping"
      continue
    else
      echo "Installing font $f..."
      cmd="cp \"$f\" \"$target\""
      echo "$cmd"
      eval "$cmd"
    fi
  done
fi

# --- --- --- --- --- --- ---
# set desired os x behavior
# --- --- --- --- --- --- ---

if running_mac_os; then
  echo "Setting up macOS behavior preferences..."
  $target_dir/bin/macos_settings
fi


# --- --- --- --- --- --- ---
# install and run Homebrew
# --- --- --- --- --- --- ---

if running_mac_os; then
  echo "Installing and running Homebrew..."
  $target_dir/bin/brewupdate
fi


# --- --- --- --- --- --- --- ---
# install desired Linux packages
# --- --- --- --- --- --- --- ---

if running_debian; then
  sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip
fi

# --- --- --- --- --- --- ---
# set the desired shell
# --- --- --- --- --- --- ---

function existing_shell() {
  if running_mac_os; then
    finger $USER|grep -o 'Shell: .*'|cut -c 8-
  elif running_debian; then
    cat /etc/passwd|grep "^$USER:"|sed 's/^.*:\(.*\)/\1/'
  fi
}

if [[ ! -f "$DESIRED_SHELL" ]]; then
  echo "Error: desired shell $DESIRED_SHELL does not exist!"
  exit -1
fi
if $(grep -q $DESIRED_SHELL /etc/shells); then
  echo "Desired shell $DESIRED_SHELL already exists in /etc/shells"
else
  echo "Appending $DESIRED_SHELL to /etc/shells..."
  echo $DESIRED_SHELL|sudo tee -a /etc/shells>/dev/null;
fi

if [[ "$(existing_shell)" == "$DESIRED_SHELL" ]]; then
  echo "User $USER is already set to use desired shell $DESIRED_SHELL"
else
  echo "Changing shell for user $USER to $DESIRED_SHELL..."
  chsh -s $DESIRED_SHELL;
fi


# --- --- --- --- --- --- ---
# python enhancements
# --- --- --- --- --- --- ---

# install pip3
if (command -v pip3 >/dev/null); then
  echo "Python pip3 already exists"
else
  echo "installing Python pip..."
  if running_debian; then
    sudo apt-get install python3-pip
  else
    echo "Error: don't know how to install pip3 on this OS!"
    exit -1
  fi
fi

# TODO: python3 only solution?
# install PIL via Pillow - needed for Ranger image previews
# python -c "import PIL" 2>/dev/null
# if [[ $? -ne 0 ]]; then
#   echo "Install Python module PIL (via pillow)..."
#   sudo /usr/local/bin/pip install pillow
# else
#   echo "Python module pillow already exists"
# fi

# install neovim-remote
if (command -v nvr >/dev/null); then
  echo "neovim-remote already installed"
else
  echo "Installing neovim-remote..."
  if running_mac_os; then
    pip3 install --user --upgrade neovim-remote
  else
    sudo pip3 install --upgrade neovim-remote
  fi
fi

# broken. should be vim-vint?
# if (command -v vint >/dev/null); then
#   echo "vint already installed"
# else
#   echo "Installing vint..."
#   /usr/local/bin/pip3 install --user --upgrade vint
# fi


# --- --- --- --- --- --- ---
# asdf
# --- --- --- --- --- --- ---

if [ -e "$target_dir/.asdf" ]; then
  echo "asdf is already installed"
else
  echo "Installing asdf..."
  git clone https://github.com/asdf-vm/asdf.git "$target_dir/.asdf"
fi
set +eu
source "$target_dir/.asdf/asdf.sh"
for p in ruby nodejs; do
  if $(asdf plugin-list | grep -qE "^${p}$"); then
    echo "asdf '$p' plugin already installed"
  else
    echo "Adding '$p' plugin to asdf..."
    asdf plugin-add $p
  fi
done
if $(gpg -k | grep -q 94AE36675C464D64BAFA68DD7434390BDBE9B9C5); then
  echo "nodejs release team GPG keys already imported"
else
  echo "Importing GPG keys for the nodejs release team..."
  bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
fi
set -eu


# --- --- --- --- --- --- ---
# Neovim plugins
# --- --- --- --- --- --- ---

# install minpac
pacpath="$HOME/.config/nvim/pack/minpac/opt/minpac"
if [[ -e "$pacpath" ]]; then
  echo "Neovim has minpac installed already"
else
  echo "Installing minpac for Neovim..."
  git clone https://github.com/k-takata/minpac.git $pacpath
fi

# install or update Neovim plugins
echo "Installing / updating Neovim plugins..."
\nvim -c "call minpac#update('', {'do': 'quit'}) | exit"


# --- --- --- --- --- --- ---
# Rust
# --- --- --- --- --- --- ---

if running_mac_os; then
  if (command -v rustup >/dev/null); then
    echo "rustup is already installed"
  else
    echo "Installing rustup and a rust..."
    /usr/local/bin/rustup-init -y
    [[ -e "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
  fi
fi
