complete -c t -f

# t-native
complete -c t -n __fish_use_subcommand -a set -d 'Set a field on a task (t-native)'
complete -c t -n __fish_use_subcommand -l done -d 'Picker over done.txt'
complete -c t -n __fish_use_subcommand -l all -d 'Picker over todo.txt + done.txt'
complete -c t -n __fish_use_subcommand -l help -d 't + todo.sh help'
complete -c t -n __fish_use_subcommand -s h -d 't + todo.sh help'

# todo.sh pass-through
complete -c t -n __fish_use_subcommand -a add -d 'Add a task'
complete -c t -n __fish_use_subcommand -a addm -d 'Add multiple tasks (newline-separated)'
complete -c t -n __fish_use_subcommand -a append -d 'Append text to a task'
complete -c t -n __fish_use_subcommand -a archive -d 'Move done tasks to done.txt'
complete -c t -n __fish_use_subcommand -a deduplicate -d 'Remove duplicate tasks'
complete -c t -n __fish_use_subcommand -a del -d 'Delete a task'
complete -c t -n __fish_use_subcommand -a depri -d 'Remove priority'
complete -c t -n __fish_use_subcommand -a do -d 'Mark a task done'
complete -c t -n __fish_use_subcommand -a help -d 'todo.sh help'
complete -c t -n __fish_use_subcommand -a list -d 'List tasks'
complete -c t -n __fish_use_subcommand -a ls -d 'List tasks'
complete -c t -n __fish_use_subcommand -a listall -d 'List all tasks (incl. done)'
complete -c t -n __fish_use_subcommand -a lsa -d 'List all tasks (incl. done)'
complete -c t -n __fish_use_subcommand -a listcon -d 'List @contexts'
complete -c t -n __fish_use_subcommand -a listpri -d 'List priority tasks'
complete -c t -n __fish_use_subcommand -a listproj -d 'List +projects'
complete -c t -n __fish_use_subcommand -a move -d 'Move task between files'
complete -c t -n __fish_use_subcommand -a mv -d 'Move task between files'
complete -c t -n __fish_use_subcommand -a prepend -d 'Prepend text to a task'
complete -c t -n __fish_use_subcommand -a pri -d 'Set priority'
complete -c t -n __fish_use_subcommand -a replace -d 'Replace a task line'
complete -c t -n __fish_use_subcommand -a report -d 'Report task/done counts'
complete -c t -n __fish_use_subcommand -a rm -d 'Delete a task'
