#!/usr/bin/env bash

# install / update Homebrew and all installed formulae

if ! [ -e '/usr/local/bin/brew' ]; then
  echo "Homebrew 'brew' binary not found in your PATH. Installing Homebrew..."
  rm -rf /usr/local/Cellar /usr/local/.git
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ -e "$HOME/.Brewfile" ]; then
  echo 'Installing formulae / apps from ~/.Brewfile'
  brew bundle --global
fi

echo 'Updating Homebrew itself'
brew update
echo 'Upgrading all installed formulae'
brew upgrade --without-x11
echo 'Cleaning up old formla versions and cache'
brew cleanup
echo 'Removing dead symlinks'
brew prune
echo 'Cleaning up old cask content'
brew cask cleanup
