#!/usr/bin/env bash

# Homebrew brew script

function install_homebrew_if_needed() {
  if ! [ -e '/usr/local/bin/brew' ]; then
    echo "Homebrew 'brew' binary not found in your PATH. Installing Homebrew..."
    rm -rf /usr/local/Cellar /usr/local/.git
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

function run_command() {
  desc=$1
  cmd=$2
  echo "$desc with '$cmd'..."
  $cmd
}

function check_or_install_formula() {
  formula_string=$@
  elements=( $formula_string )
  formula=${elements[0]}
  echo "Checking if '$formula' is installed..."
  if `brew list $formula >/dev/null 2>&1`; then
    echo "Formula '$formula' already installed"
  else  
    echo "Formula '$formula' not yet installed."
    run_command "Installing '$formula'" "brew install $formula_string"
  fi
}

function check_or_install_cask() {
  cask=$1
  echo "Checking if '$cask' is installed..."
  if `brew cask list $cask >/dev/null 2>&1`; then
    echo "Cask '$cask' already installed."
  else
    echo "Cask '$cask' not yet installed."
    run_command "Installing '$cask'" "brew cask install $cask"
  fi 
}


install_homebrew_if_needed

run_command 'Updating Homebrew itself' 'brew update'
run_command 'Upgrading all installed formulae' 'brew upgrade --without-x11'

declare -a desired_formulae=(awscli
                             bash
                             bash-completion
                             coreutils
                             ctags
                             findutils
                             gnu-sed
                             imagemagick
                             'jmeter --with-plugins'
                             jq
                             libxml2
                             libxslt
                             libyaml
                             'macvim --override-system-vim'
                             maven
                             mongodb
                             mysql
                             openssl
                             reattach-to-user-namespace
                             sqlite
                             the_silver_searcher
                             tig
                             tmux
                             watch
                             zsh)

# install desired formulae
for formula in "${desired_formulae[@]}"; do
  check_or_install_formula $formula
done

# set up brew cask
run_command 'Tapping homebrew-cask' 'brew tap caskroom/homebrew-cask'
check_or_install_formula brew-cask
run_command 'Tapping versions' 'brew tap caskroom/versions'

declare -a desired_casks=(adium
                          alfred
                          appcleaner
                          bettertouchtool
                          caffeine
                          dropbox
                          evernote
                          fantastical
                          firefox
                          google-chrome
                          iterm2
                          java
                          mou
                          nvalt
                          onepassword
                          sequel-pro
                          slack
                          spotify
                          steam
                          vagrant
                          virtualbox
                          vlc)

# install desired casks
for cask in "${desired_casks[@]}"; do
  check_or_install_cask $cask
done

# these are currently coming from the Mac App Store, not Cask
# xee
# clear

# remove old cruft
run_command 'Cleaning up old formula versions and cache' 'brew cleanup'
run_command 'Removing dead symlinks' 'brew prune'
